ALTER TABLE "ElecScenario" ADD COLUMN "sqft" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ElecScenario" ADD COLUMN "smallAppCircuits" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "ElecScenario" ADD COLUMN "laundry" BOOLEAN NOT NULL DEFAULT true;
